const prettierConfig = {
  semi: true,
  singleQuote: true,
  tabWidth: 2,
  useTabs: false,
  trailingComma: 'es6',
  bracketSpacing: true,
  arrowParens: 'always',
  printWidth: 100,
  endOfLine: 'lf',
  jsxSingleComma: false,
  quoteProps: 'as-needed',
  tailwindFunctions: ['clsx', 'cva'],
  plugins: ['@trivago/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
  importOrder: [
    '^react$',
    '^next',
    '<THIRD_PARTY_MODULES>',
    '^@/app',
    '^@/components',
    '^@/api',
    '^@/store',
    '^@/hooks',
    '^@/lib',
    '^@/styles',
    '^@/public',
    '^[./]',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};

export default prettierConfig;
